// Auto-generated by capman AI
// Review before committing

module.exports = {
  "app": "conversational-ai-assistant",
  "baseUrl": "https://api.conversational-ai-assistant.com",
  "capabilities": [
    {
      "id": "generate_text",
      "name": "Text Generation",
      "description": "Generate human-like text based on a given prompt or topic",
      "examples": [
        "Write a story about a character who learns a new skill",
        "Create a product description for a new smartwatch",
        "Compose an email to a friend about a recent trip"
      ],
      "params": [
        {
          "name": "prompt",
          "description": "The text prompt to generate content from",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "text"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/generate/text"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "code_generation",
      "name": "Code Generation",
      "description": "Generate code snippets in various programming languages based on a given specification",
      "examples": [
        "Create a Python function to sort a list of numbers",
        "Write a JavaScript script to validate user input",
        "Generate a Java class to represent a bank account"
      ],
      "params": [
        {
          "name": "language",
          "description": "The programming language to generate code in",
          "required": true,
          "source": "user_query"
        },
        {
          "name": "specification",
          "description": "The specification of the code to generate",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "code"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/generate/code"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "summarization",
      "name": "Summarization",
      "description": "Summarize a given piece of text into a shorter summary",
      "examples": [
        "Summarize a news article about a recent event",
        "Summarize a research paper on a complex topic",
        "Summarize a book review"
      ],
      "params": [
        {
          "name": "text",
          "description": "The text to summarize",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "summary"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/summarize"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "recommendation",
      "name": "Recommendation",
      "description": "Provide recommendations based on a given context or user input",
      "examples": [
        "Recommend a movie based on my favorite genre",
        "Suggest a book based on my reading history",
        "Propose a travel destination based on my interests"
      ],
      "params": [
        {
          "name": "context",
          "description": "The context or user input to provide recommendations for",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "recommendations"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/recommend"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "task_automation",
      "name": "Task Automation",
      "description": "Automate tasks such as drafting emails, brainstorming ideas, or explaining complex topics",
      "examples": [
        "Draft an email to a client about a project update",
        "Brainstorm ideas for a new marketing campaign",
        "Explain a complex topic like artificial intelligence to a beginner"
      ],
      "params": [
        {
          "name": "task",
          "description": "The task to automate",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "result"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/automate"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    }
  ]
}
