// Auto-generated by capman AI
// Review before committing

module.exports = {
  "app": "project-management",
  "baseUrl": "https://api.your-app.com",
  "capabilities": [
    {
      "id": "create_project",
      "name": "Create Project",
      "description": "Allows users to create a new project with specified parameters.",
      "examples": [
        "Create a project for Q1 Marketing",
        "Start development project for new feature"
      ],
      "params": [
        {
          "name": "project_name",
          "description": "The name of the project",
          "required": true,
          "source": "user_query"
        },
        {
          "name": "deadline",
          "description": "The due date for the project",
          "required": false,
          "source": "user_query"
        }
      ],
      "returns": [
        "project"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/projects"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "add_task",
      "name": "Add Task",
      "description": "Allows users to add a task to a specified project.",
      "examples": [
        "Add task to complete design",
        "Create a task for code review"
      ],
      "params": [
        {
          "name": "project_id",
          "description": "The ID of the project to add a task to",
          "required": true,
          "source": "user_query"
        },
        {
          "name": "task_name",
          "description": "The name of the task to be added",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "task"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/projects/{project_id}/tasks"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "assign_member",
      "name": "Assign Team Member",
      "description": "Enables the assignment of team members to specific tasks.",
      "examples": [
        "Assign John Doe to the marketing campaign",
        "Allocate Jane Smith for the new feature task"
      ],
      "params": [
        {
          "name": "task_id",
          "description": "The ID of the task to assign a member to",
          "required": true,
          "source": "user_query"
        },
        {
          "name": "user_id",
          "description": "The ID of the user being assigned",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "task_assignment"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/tasks/{task_id}/assign"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "track_deadline",
      "name": "Track Deadline",
      "description": "Enables users to check the deadlines of projects and tasks.",
      "examples": [
        "Check deadlines for all tasks in project X",
        "View upcoming deadlines for the development project"
      ],
      "params": [
        {
          "name": "project_id",
          "description": "The ID of the project to check deadlines for",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "deadlines"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/projects/{project_id}/deadlines"
          }
        ]
      },
      "privacy": {
        "level": "public"
      }
    },
    {
      "id": "manage_billing",
      "name": "Manage Billing",
      "description": "Allows admins to manage billing details for the workspace.",
      "examples": [
        "Update billing details",
        "View current subscription plan"
      ],
      "params": [
        {
          "name": "workspace_id",
          "description": "The ID of the workspace for billing management",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "billing_info"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/workspaces/{workspace_id}/billing"
          }
        ]
      },
      "privacy": {
        "level": "admin"
      }
    },
    {
      "id": "invite_user",
      "name": "Invite User",
      "description": "Enables admins to send invitations to users for joining the workspace.",
      "examples": [
        "Invite new member to the project team",
        "Send invitation to user@example.com"
      ],
      "params": [
        {
          "name": "email",
          "description": "The email address of the user to invite",
          "required": true,
          "source": "user_query"
        },
        {
          "name": "workspace_id",
          "description": "The ID of the workspace to invite the user to",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "invitation"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/workspaces/{workspace_id}/invite"
          }
        ]
      },
      "privacy": {
        "level": "admin"
      }
    }
  ]
}
