// Auto-generated by capman from OpenAPI spec
    // Review and adjust before committing

    module.exports = {
  "app": "swagger-petstore",
  "baseUrl": "https://petstore.swagger.io/v2",
  "capabilities": [
    {
      "id": "find_pets_by_status",
      "name": "Finds Pets by status",
      "description": "Multiple status values can be provided with comma separated strings",
      "examples": [
        "Finds Pets by status",
        "Multiple status values can be provided with comma separated strings",
        "Finds Pets by status by status"
      ],
      "params": [
        {
          "name": "status",
          "description": "Status values that need to be considered for filter",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "findByStatus"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/pet/findByStatus"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "find_pets_by_tags",
      "name": "Finds Pets by tags",
      "description": "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
      "examples": [
        "Finds Pets by tags",
        "Multiple tags can be provided with comma separated strings",
        "Finds Pets by tags by tags"
      ],
      "params": [
        {
          "name": "tags",
          "description": "Tags to filter by",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "findByTags"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/pet/findByTags"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "get_pet_by_id",
      "name": "Find pet by ID",
      "description": "Returns a single pet",
      "examples": [
        "Find pet by ID",
        "Returns a single pet",
        "Find pet by ID by pet id"
      ],
      "params": [
        {
          "name": "pet_id",
          "description": "ID of pet to return",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "pet"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/pet/{petId}"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "get_inventory",
      "name": "Returns pet inventories by status",
      "description": "Returns a map of status codes to quantities",
      "examples": [
        "Returns pet inventories by status",
        "Returns a map of status codes to quantities"
      ],
      "params": [],
      "returns": [
        "inventory"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/store/inventory"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "get_order_by_id",
      "name": "Find purchase order by ID",
      "description": "For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions",
      "examples": [
        "Find purchase order by ID",
        "For valid response try integer IDs with value >= 1 and <= 10",
        "Find purchase order by ID by order id"
      ],
      "params": [
        {
          "name": "order_id",
          "description": "ID of pet that needs to be fetched",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "order"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "GET",
            "path": "/store/order/{orderId}"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "delete_order",
      "name": "Delete purchase order by ID",
      "description": "For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors",
      "examples": [
        "Delete purchase order by ID",
        "For valid response try integer IDs with positive integer value",
        "Delete purchase order by ID by order id"
      ],
      "params": [
        {
          "name": "order_id",
          "description": "ID of the order that needs to be deleted",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "order"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "DELETE",
            "path": "/store/order/{orderId}"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "update_user",
      "name": "Updated user",
      "description": "This can only be done by the logged in user.",
      "examples": [
        "Updated user",
        "This can only be done by the logged in user",
        "Updated user by username and body"
      ],
      "params": [
        {
          "name": "username",
          "description": "name that need to be updated",
          "required": true,
          "source": "user_query"
        },
        {
          "name": "body",
          "description": "Updated user object",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "user"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "PUT",
            "path": "/user/{username}"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "delete_user",
      "name": "Delete user",
      "description": "This can only be done by the logged in user.",
      "examples": [
        "Delete user",
        "This can only be done by the logged in user",
        "Delete user by username"
      ],
      "params": [
        {
          "name": "username",
          "description": "The name that needs to be deleted",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "user"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "DELETE",
            "path": "/user/{username}"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    },
    {
      "id": "create_user",
      "name": "Create user",
      "description": "This can only be done by the logged in user.",
      "examples": [
        "Create user",
        "This can only be done by the logged in user",
        "Create user by body"
      ],
      "params": [
        {
          "name": "body",
          "description": "Created user object",
          "required": true,
          "source": "user_query"
        }
      ],
      "returns": [
        "user"
      ],
      "resolver": {
        "type": "api",
        "endpoints": [
          {
            "method": "POST",
            "path": "/user"
          }
        ]
      },
      "privacy": {
        "level": "user_owned"
      }
    }
  ]
}
    